{bookName:"Бытие",
bookKeyVerse:"1,1",

bookSubject:"Происхождение",
bookKeyWord:"в начале",
bookMainTheme:"Начало всего",
BookDateWriting:" c. 1450 вс-1400 вс",
bookAuthor:"Моисей",
bookRecipient:"Израиль",
bookPlaceWriting:"Египет и Ханаан",
bookChapters:"50",
bookVerses:"1533",
bookAllWords:"28420",
bookCovenant:"ВЗ",
bookGanre:"Пятикнижье"}
{bookName:"Исход",
bookKeyVerse:"3,8",
bookSubject:"Избавление",
bookKeyWord:"от руки",
bookMainTheme:"Избавление из рабства",
BookDateWriting:" c. 1445 вс-1440 вс",
bookAuthor:"Моисей",
bookRecipient:"Израиль",
bookPlaceWriting:"Египет и Ханаан",
bookChapters:"40",
bookVerses:"1213",
bookAllWords:"24230",
bookCovenant:"ВЗ",
bookGanre:"Пятикнижье"}
{bookName:"Левит",
bookKeyVerse:"19,2",
bookSubject:"Святость",
bookKeyWord:"общество",
bookMainTheme:"Святое собрание",
BookDateWriting:" c. 1445 вс—1400 вс",
bookAuthor:"Моисей",
bookRecipient:"Израиль",
bookPlaceWriting:"Синай и Ханаан",
bookChapters:"27",
bookVerses:"858",
bookAllWords:"16849",
bookCovenant:"ВЗ",
bookGanre:"Пятикнижье"}
{bookName:"Числа",
bookKeyVerse:"14,22-23",
bookSubject:"Непослушание ",
bookKeyWord:"Гласу Божьему",
bookMainTheme:"Непослушание голосу Божьему",
BookDateWriting:"c. 1445 вс-1400 вс",
bookAuthor:"Моисей",
bookRecipient:"Израиль",
bookPlaceWriting:"Синай и Ханаан",
bookChapters:"36",
bookVerses:"1288",
bookAllWords:"22478",
bookCovenant:"ВЗ",
bookGanre:"Пятикнижье"}
{bookName:"Второзаконие",
bookKeyVerse:"6;3",
bookSubject:"Послушание",
bookKeyWord:"заповедям",
bookMainTheme:"Послушание Божьим заповедям",
BookDateWriting:" c. 1401 вс-1400 вс",
bookAuthor:"Моисей",
bookRecipient:"Израиль",
bookPlaceWriting:"Равнины Моава",
bookChapters:"34",
bookVerses:"959",
bookAllWords:"20946",
bookCovenant:"ВЗ",
bookGanre:"Пятикнижье"}
{bookName:"Иисус Навин",
bookKeyVerse:"21;45",
bookSubject:"Верность",
bookKeyWord:"Бога",
bookMainTheme:"Верность Бога Своему народу",
BookDateWriting:" c. 1405 вс—1383 вс",
bookAuthor:"Иисус Навин",
bookRecipient:"Израиль",
bookPlaceWriting:"Ханаан",
bookChapters:"24",
bookVerses:"85",
bookAllWords:"1908",
bookCovenant:"ВЗ",
bookGanre:"Исторические"}
{bookName:"Судьи",
bookKeyVerse:"21;24-25",
bookSubject:"Неверность",
bookKeyWord:"Израиля",
bookMainTheme:"Неверность народа Своегму Богу",
BookDateWriting:" c. 1086 вс-1004 вс",
bookAuthor:"Неизвестен",
bookRecipient:"Израиль",
bookPlaceWriting:"Ханаан",
bookChapters:"21",
bookVerses:"661",
bookAllWords:"13540",
bookCovenant:"ВЗ",
bookGanre:"Исторические"}
{bookName:"Руфь",
bookKeyVerse:"1,9;1,16; 3,1",
bookSubject:"Пристанище",
bookKeyWord:"Поиск",
bookMainTheme:"Поиск пристанища",
BookDateWriting:" c. 1046 вс-1035 вс",
bookAuthor:"Неизвестен",
bookRecipient:"Израиль",
bookPlaceWriting:"Ханаан",
bookChapters:"4",
bookVerses:"618",
bookAllWords:"13471",
bookCovenant:"ВЗ",
bookGanre:"Исторические"}
{bookName:"1-ая Царств",
bookKeyVerse:"16,7.12",
bookSubject:"Избранник",
bookKeyWord:"Бога",
bookMainTheme:"Божий избранник",
BookDateWriting:" c. 1050 вс-750 вс",
bookAuthor:"Неизвестен",
bookRecipient:"Израиль",
bookPlaceWriting:"Израиль и Иудея",
bookChapters:"31",
bookVerses:"811",
bookAllWords:"18609",
bookCovenant:"ВЗ",
bookGanre:"Исторические"}
{bookName:"2-ая Царств",
bookKeyVerse:"7;16",
bookSubject:"Царство",
bookKeyWord:"навеки",
bookMainTheme:"Обетование вечного Царства",
BookDateWriting:" c. 1050 вс-750 вс",
bookAuthor:"Неизвестен",
bookRecipient:"Израиль",
bookPlaceWriting:"Израиль и Иудея",
bookChapters:"24",
bookVerses:"695",
bookAllWords:"15082",
bookCovenant:"ВЗ",
bookGanre:"Исторические"}
{bookName:"3-ая Царств",
bookKeyVerse:"11;35-36",
bookSubject:"Преданность",
bookKeyWord:"сердца",
bookMainTheme:"Преданность сердца",
BookDateWriting:" 590 вс-570 вс",
bookAuthor:"Неизвестен",
bookRecipient:"Израиль",
bookPlaceWriting:"В плену в Вавилоне",
bookChapters:"22",
bookVerses:"816",
bookAllWords:"17880",
bookCovenant:"ВЗ",
bookGanre:"Исторические"}
{bookName:"4-ая Царств",
bookKeyVerse:"17,23",
bookSubject:"Отвержение",
bookKeyWord:"от лица Божьего",
bookMainTheme:"Отвержение народа Божьего",
BookDateWriting:" 590 вс-550 вс",
bookAuthor:"Неизвестен",
bookRecipient:"Израиль",
bookPlaceWriting:"В плену в Вавилоне",
bookChapters:"25",
bookVerses:"719",
bookAllWords:"16748",
bookCovenant:"ВЗ",
bookGanre:"Исторические"}
{bookName:"1-ая Паралипоменон",
bookKeyVerse:"17,11-14",
bookSubject:"Верность Бога",
bookKeyWord:"Завету",
bookMainTheme:"Верность Бога Своему завету",
BookDateWriting:" c. 450 вс-425 вс ",
bookAuthor:"Ездра",
bookRecipient:"Израиль",
bookPlaceWriting:"Иудея",
bookChapters:"29",
bookVerses:"942",
bookAllWords:"14295",
bookCovenant:"ВЗ",
bookGanre:"Исторические"}
{bookName:"2-ая Паралипоменон",
bookKeyVerse:"13:10",
bookSubject:"Господь",
bookKeyWord:"ценность",
bookMainTheme:"Господь - высшая ценость народа",
BookDateWriting:" c. 450 вс-425 вс",
bookAuthor:"Ездра",
bookRecipient:"Израиль",
bookPlaceWriting:"Иудея",
bookChapters:"36",
bookVerses:"822",
bookAllWords:"19033",
bookCovenant:"ВЗ",
bookGanre:"Исторические"}
{bookName:"Ездры",
bookKeyVerse:"6;15",
bookSubject:"Дом Божий",
bookKeyWord:"Восстановление",
bookMainTheme:"Восстановление Дома Божьего",
BookDateWriting:" c. 457 вс-444 вс",
bookAuthor:"Ездра",
bookRecipient:"Израиль",
bookPlaceWriting:"Иудея",
bookChapters:"10",
bookVerses:"280",
bookAllWords:"5201",
bookCovenant:"ВЗ",
bookGanre:"Исторические"}
{bookName:"Неемии",
bookKeyVerse:"4,17",
bookSubject:"Стена",
bookKeyWord:"Строившие",
bookMainTheme:"Духовное укрепление",
BookDateWriting:" c. 445 вс-430 вс",
bookAuthor:"Неемия",
bookRecipient:"Израиль",
bookPlaceWriting:"Иудея",
bookChapters:"13",
bookVerses:"406",
bookAllWords:"7558",
bookCovenant:"ВЗ",
bookGanre:"Исторические"}
{bookName:"Есфирь",
bookKeyVerse:"4,13-16",
bookSubject:"Провидение",
bookKeyWord:"Пурим",
bookMainTheme:"Провидение Божье в спасении",
BookDateWriting:" c. 464 вс-435 вс",
bookAuthor:"Неизвестен",
bookRecipient:"Израиль",
bookPlaceWriting:"Персия",
bookChapters:"10",
bookVerses:"167",
bookAllWords:"5773",
bookCovenant:"ВЗ",
bookGanre:"Исторические"}
{bookName:"Иов",
bookKeyVerse:"38,2 и 42,3",
bookSubject:"Провидение",
bookKeyWord:"разумение",
bookMainTheme:"Понимание Божьего провидения",
BookDateWriting:" Unknown  ",
bookAuthor:"Неизвестен",
bookRecipient:"",
bookPlaceWriting:"Месопотамия (Уц)",
bookChapters:"42",
bookVerses:"1070",
bookAllWords:"13581",
bookCovenant:"ВЗ",
bookGanre:"Поэтические"}
{bookName:"Псалтырь",
bookKeyVerse:"28,2",
bookSubject:"Поклонение",
bookKeyWord:"Богу",
bookMainTheme:"Поклонение Богу",
BookDateWriting:" c. 1410 вс-430 вс",
bookAuthor:"Давид и",
bookRecipient:"",
bookPlaceWriting:"Израиль",
bookChapters:"150",
bookVerses:"2516",
bookAllWords:"30197",
bookCovenant:"ВЗ",
bookGanre:"Поэтические"}
{bookName:"Притчи",
bookKeyVerse:"13,1",
bookSubject:"Наставления",
bookKeyWord:"сыновьям",
bookMainTheme:"Наставления сыновьям",
BookDateWriting:" c. 950 вс—700 вс",
bookAuthor:"Соломон",
bookRecipient:"Потомки",
bookPlaceWriting:"Израиль",
bookChapters:"31",
bookVerses:"918",
bookAllWords:"10496",
bookCovenant:"ВЗ",
bookGanre:"Поэтические"}
{bookName:"Екклесиаст",
bookKeyVerse:"1;2  11",
bookSubject:"Суета",
bookKeyWord:"под солнцем",
bookMainTheme:"Суетность земной жизни",
BookDateWriting:" c. 935 вс",
bookAuthor:"Соломон",
bookRecipient:"",
bookPlaceWriting:"Иерусалим",
bookChapters:"12",
bookVerses:"222",
bookAllWords:"4159",
bookCovenant:"ВЗ",
bookGanre:"Поэтические"}
{bookName:"Песнь Песней",
bookKeyVerse:"6;3",
bookSubject:"Любовь",
bookKeyWord:"в браке",
bookMainTheme:"Любовь в браке",
BookDateWriting:" c. 965 вс",
bookAuthor:"Соломон",
bookRecipient:"",
bookPlaceWriting:"Иерусалим",
bookChapters:"8",
bookVerses:"116",
bookAllWords:"1926",
bookCovenant:"ВЗ",
bookGanre:"Поэтические"}
{bookName:"Исайя",
bookKeyVerse:"53,4-6",
bookSubject:"Спасение",
bookKeyWord:"путь",
bookMainTheme:"Путь спасения",
BookDateWriting:" c. 740 вс-680 вс",
bookAuthor:"Исайя",
bookRecipient:"Иудея",
bookPlaceWriting:"Иудея",
bookChapters:"66",
bookVerses:"1291",
bookAllWords:"25734",
bookCovenant:"ВЗ",
bookGanre:"Пророческие"}
{bookName:"Иеремия",
bookKeyVerse:"31,31",
bookSubject:"Власть Бога",
bookKeyWord:"завет",
bookMainTheme:"Необходимость обновления завета",
BookDateWriting:" c. 626 вс-580 вс",
bookAuthor:"Иеремия",
bookRecipient:"Иудея",
bookPlaceWriting:"Иудея",
bookChapters:"52",
bookVerses:"1364",
bookAllWords:"30410",
bookCovenant:"ВЗ",
bookGanre:"Пророческие"}
{bookName:"Плач Иеремии (Плача)",
bookKeyVerse:"3,22",
bookSubject:"Грех",
bookKeyWord:"Надежда на избавление",
bookMainTheme:"Надежда на избавление от греха",
BookDateWriting:" c. 586 вс-584 вс",
bookAuthor:"Иеремия",
bookRecipient:"Иудея",
bookPlaceWriting:"Вавилон",
bookChapters:"5",
bookVerses:"154",
bookAllWords:"2363",
bookCovenant:"ВЗ",
bookGanre:"Пророческие"}
{bookName:"Иезекиль",
bookKeyVerse:"38;23",
bookSubject:"Слава Божья",
bookKeyWord:"явление",
bookMainTheme:"Явление славы Божьей над Израилем",
BookDateWriting:" c. 587 вс-565 вс",
bookAuthor:"Иезекиль",
bookRecipient:"Иудея",
bookPlaceWriting:"Вавилон",
bookChapters:"48",
bookVerses:"1273",
bookAllWords:"28355",
bookCovenant:"ВЗ",
bookGanre:"Пророческие"}
{bookName:"Даниил",
bookKeyVerse:"2,44",
bookSubject:"Царство",
bookKeyWord:"Всевышнего",
bookMainTheme:"Установление Царства Всевышнего",
BookDateWriting:" c. 605 вс-530 вс",
bookAuthor:"Даниил",
bookRecipient:"Иудея",
bookPlaceWriting:"Вавилон",
bookChapters:"12",
bookVerses:"424",
bookAllWords:"9371",
bookCovenant:"ВЗ",
bookGanre:"Пророческие"}
{bookName:"Осия",
bookKeyVerse:"13,9",
bookSubject:"Неверность",
bookKeyWord:"Израиля",
bookMainTheme:"Неверность народа Своему Богу",
BookDateWriting:" c. 755 вс-710 вс",
bookAuthor:"Осия",
bookRecipient:"Иудея",
bookPlaceWriting:"Израиль",
bookChapters:"14",
bookVerses:"197",
bookAllWords:"3734",
bookCovenant:"ВЗ",
bookGanre:"Пророческие"}
{bookName:"Иоиль",
bookKeyVerse:"2,1",
bookSubject:"День  Господень",
bookKeyWord:"наступление",
bookMainTheme:"Наступление Дня Господнего",
BookDateWriting:" Unknown",
bookAuthor:"Иоиль",
bookRecipient:"Иудея",
bookPlaceWriting:"Иудея",
bookChapters:"3",
bookVerses:"73",
bookAllWords:"1393",
bookCovenant:"ВЗ",
bookGanre:"Пророческие"}
{bookName:"Амос",
bookKeyVerse:"5,4",
bookSubject:"Поиск",
bookKeyWord:"Спасителя",
bookMainTheme:"Поиск Спасителя",
BookDateWriting:" c. 760 вс-750 вс",
bookAuthor:"Амос",
bookRecipient:"Иудея",
bookPlaceWriting:"Израиль",
bookChapters:"9",
bookVerses:"146",
bookAllWords:"2970",
bookCovenant:"ВЗ",
bookGanre:"Пророческие"}
{bookName:"Авдий",
bookKeyVerse:"1,15",
bookSubject:"Едом",
bookKeyWord:"воздаяние",
bookMainTheme:"Воздаяние нечестивым",
BookDateWriting:" c. 586 вс",
bookAuthor:"Авдий",
bookRecipient:"Иудея",
bookPlaceWriting:"Иудея",
bookChapters:"1",
bookVerses:"21",
bookAllWords:"467",
bookCovenant:"ВЗ",
bookGanre:"Пророческие"}
{bookName:"Иона",
bookKeyVerse:"4,2",
bookSubject:"Милосердие",
bookKeyWord:"бедствие",
bookMainTheme:"Преображающее милосердие",
BookDateWriting:" c. 783 вс-753вс",
bookAuthor:"Иона",
bookRecipient:"Иудея",
bookPlaceWriting:"Ниневия",
bookChapters:"4",
bookVerses:"48",
bookAllWords:"984",
bookCovenant:"ВЗ",
bookGanre:"Пророческие"}
{bookName:"Михей",
bookKeyVerse:"7,18",
bookSubject:"суд",
bookKeyWord:"милость",
bookMainTheme:"Милостивый суд",
BookDateWriting:" c. 739 вс-686 вс",
bookAuthor:"Михей",
bookRecipient:"Иудея",
bookPlaceWriting:"Израиль и Иудея",
bookChapters:"7",
bookVerses:"105",
bookAllWords:"2173",
bookCovenant:"ВЗ",
bookGanre:"Пророческие"}
{bookName:"Наум",
bookKeyVerse:"1,8-9",
bookSubject:"Разрушение",
bookKeyWord:"до основания",
bookMainTheme:"Истребление Ниневии",
BookDateWriting:" c. 664 вс-612 вс",
bookAuthor:"Наум",
bookRecipient:"Иудея",
bookPlaceWriting:"Иудея и Ненивия",
bookChapters:"3",
bookVerses:"47",
bookAllWords:"865",
bookCovenant:"ВЗ",
bookGanre:"Пророческие"}
{bookName:"Аввакум",
bookKeyVerse:"2;4",
bookSubject:"Жизнь",
bookKeyWord:"праведного",
bookMainTheme:"Жизнь праведного в нечестивом мире",
BookDateWriting:" c. 609 вс-597вс",
bookAuthor:"Аввакум",
bookRecipient:"Иудея",
bookPlaceWriting:"Иудея",
bookChapters:"3",
bookVerses:"56",
bookAllWords:"1056",
bookCovenant:"ВЗ",
bookGanre:"Пророческие"}
{bookName:"Софония",
bookKeyVerse:"2,3",
bookSubject:"День Господень",
bookKeyWord:"сокрытие",
bookMainTheme:"Укрытие в День Господень",
BookDateWriting:" c. 640 вс-628 вс",
bookAuthor:"Софония",
bookRecipient:"Иудея",
bookPlaceWriting:"Иудея",
bookChapters:"3",
bookVerses:"53",
bookAllWords:"1087",
bookCovenant:"ВЗ",
bookGanre:"Пророческие"}
{bookName:"Аггей",
bookKeyVerse:"2,9",
bookSubject:"Дом Божий",
bookKeyWord:"Слава",
bookMainTheme:"Слава дома Божьего",
BookDateWriting:" c. 520 вс",
bookAuthor:"Аггей",
bookRecipient:"Иудея",
bookPlaceWriting:"Иудея",
bookChapters:"2",
bookVerses:"38",
bookAllWords:"788",
bookCovenant:"ВЗ",
bookGanre:"Пророческие"}
{bookName:"Захария",
bookKeyVerse:"1,3",
bookSubject:"Обращение",
bookKeyWord:"к Господу",
bookMainTheme:"Обращение к Господу",
BookDateWriting:" c. 520 вс-519 вс",
bookAuthor:"Захария",
bookRecipient:"Иудея",
bookPlaceWriting:"Иудея",
bookChapters:"14",
bookVerses:"211",
bookAllWords:"4462",
bookCovenant:"ВЗ",
bookGanre:"Пророческие"}
{bookName:"Малахия",
bookKeyVerse:"2,11",
bookSubject:"Поведение",
bookKeyWord:"Вероломно",
bookMainTheme:"Вероломное поведение",
BookDateWriting:" c. 430 вс-400 вс",
bookAuthor:"Малахия",
bookRecipient:"Иудея",
bookPlaceWriting:"Иудея",
bookChapters:"4",
bookVerses:"55",
bookAllWords:"1306",
bookCovenant:"ВЗ",
bookGanre:"Пророческие"}
{bookName:"Евангелие от Матфея",
bookKeyVerse:"2,2",
bookSubject:"Царь",
bookKeyWord:"Израиля",
bookMainTheme:"Иисус -Царь от Бога",
BookDateWriting:" c. ad 60",
bookAuthor:"Матфей",
bookRecipient:"Евреи Сирии",
bookPlaceWriting:"Иудея",
bookChapters:"28",
bookVerses:"1071",
bookAllWords:"16961",
bookCovenant:"НЗ",
bookGanre:"Евангелия"}
{bookName:"Евангелие от Марка",
bookKeyVerse:"10,45",
bookSubject:"Слуга",
bookKeyWord:"народа Божьего",
bookMainTheme:"Иисус - Божий Слуга",
BookDateWriting:" c. ad 58",
bookAuthor:"Марк",
bookRecipient:"Римлянам",
bookPlaceWriting:"Рим",
bookChapters:"16",
bookVerses:"678",
bookAllWords:"10661",
bookCovenant:"НЗ",
bookGanre:"Евангелия"}
{bookName:"Евангелие от Луки",
bookKeyVerse:"19:10",
bookSubject:"Сын",
bookKeyWord:"Человеческий",
bookMainTheme:"Иисус - Сын Человеческий",
BookDateWriting:" c. ad 60-ad 62",
bookAuthor:"Лука",
bookRecipient:"Язычники",
bookPlaceWriting:"Кесария",
bookChapters:"24",
bookVerses:"1151",
bookAllWords:"18212",
bookCovenant:"НЗ",
bookGanre:"Евангелия"}
{bookName:"Евангелие от Иоанна",
bookKeyVerse:"20,31",
bookSubject:"Сын Божий",
bookKeyWord:"уверовали",
bookMainTheme:"Иисус - Сын Божий",
BookDateWriting:" c. ad 85-ad 95",
bookAuthor:"Иоанн",
bookRecipient:"Христианам Ефеса",
bookPlaceWriting:"Малая Азия",
bookChapters:"21",
bookVerses:"879",
bookAllWords:"14429",
bookCovenant:"НЗ",
bookGanre:"Евангелия"}
{bookName:"Деяния",
bookKeyVerse:"1,8",
bookSubject:"Свидетельство",
bookKeyWord:"до края земли",
bookMainTheme:"Свидетельство по всему миру",
BookDateWriting:"c. ad 60-ad 62 ",
bookAuthor:"Лука",
bookRecipient:"Язычники",
bookPlaceWriting:"Кесария и Рим",
bookChapters:"28",
bookVerses:"1006",
bookAllWords:"17381",
bookCovenant:"НЗ",
bookGanre:"Исторические"}
{bookName:"Римлянам",
bookKeyVerse:"3,28",
bookSubject:"Праведность",
bookKeyWord:"для верующих",
bookMainTheme:"Оправдание верой",
BookDateWriting:" c. ad 57",
bookAuthor:"Павел",
bookRecipient:"Христианам Рима",
bookPlaceWriting:"Коринф",
bookChapters:"16",
bookVerses:"433",
bookAllWords:"6647",
bookCovenant:"НЗ",
bookGanre:"Эпистолярный"}
{bookName:"1-е Коринфянам",
bookKeyVerse:"3,11",
bookSubject:"Основание",
bookKeyWord:"Христос",
bookMainTheme:"Христос - единое основание",
BookDateWriting:" c. ad 56",
bookAuthor:"Павел",
bookRecipient:"Христианам Коринфа",
bookPlaceWriting:"Ефес",
bookChapters:"16",
bookVerses:"437",
bookAllWords:"6727",
bookCovenant:"НЗ",
bookGanre:"Эпистолярный"}
{bookName:"2-е Коринфянам",
bookKeyVerse:"1,3-4",
bookSubject:"Утешение",
bookKeyWord:"в служении",
bookMainTheme:"Утешение в служении",
BookDateWriting:" c. ad 56",
bookAuthor:"Павел",
bookRecipient:"Христианам Коринфа",
bookPlaceWriting:"Филиппы",
bookChapters:"13",
bookVerses:"255",
bookAllWords:"4501",
bookCovenant:"НЗ",
bookGanre:"Эпистолярный"}
{bookName:"Галатам",
bookKeyVerse:"5,1",
bookSubject:"Свобода",
bookKeyWord:"даровал",
bookMainTheme:"Дар свободы во Христе",
BookDateWriting:" c. ad 50-ad 55",
bookAuthor:"Павел",
bookRecipient:"Христианам Антиохии, Иконии, Листры, Дервии, Южной Галати",
bookPlaceWriting:"Малая Азия",
bookChapters:"6",
bookVerses:"140",
bookAllWords:"2189",
bookCovenant:"НЗ",
bookGanre:"Эпистолярный"}
{bookName:"Ефесянам",
bookKeyVerse:"4,4",
bookSubject:"Единство",
bookKeyWord:"Тела Христова",
bookMainTheme:"Единство Тела Христова",
BookDateWriting:" c. ad 60-ad 64",
bookAuthor:"Павел",
bookRecipient:"Христианам в Ефесе",
bookPlaceWriting:"В заключении в Риме",
bookChapters:"6",
bookVerses:"155",
bookAllWords:"2115",
bookCovenant:"НЗ",
bookGanre:"Эпистолярный"}
{bookName:"Филиппицам",
bookKeyVerse:"4,4",
bookSubject:"Радость",
bookKeyWord:"в Господе",
bookMainTheme:"Радость в Господе",
BookDateWriting:"c. ad 60-ad 64 ",
bookAuthor:"Павел",
bookRecipient:"Христианам в Филиппах",
bookPlaceWriting:"В заключении в Риме",
bookChapters:"4",
bookVerses:"104",
bookAllWords:"1603",
bookCovenant:"НЗ",
bookGanre:"Эпистолярный"}
{bookName:"Колоссянам",
bookKeyVerse:"1;18",
bookSubject:"Главенство",
bookKeyWord:"Христа",
bookMainTheme:"Главенство Христа",
BookDateWriting:"c. ad 60–ad 64",
bookAuthor:"Павел",
bookRecipient:"Христианам в Колоссах",
bookPlaceWriting:"В заключении в Риме",
bookChapters:"4",
bookVerses:"95",
bookAllWords:"1444",
bookCovenant:"НЗ",
bookGanre:"Эпистолярный"}
{bookName:"1-е Фессалоникийцам",
bookKeyVerse:"1,9-10",
bookSubject:"Пришествие",
bookKeyWord:"ожидание",
bookMainTheme:"Жизнь Церкви в ожидании 2-го пришествия",
BookDateWriting:" c. ad 49-ad 54  ",
bookAuthor:"Павел",
bookRecipient:"Христианам Фессалоники",
bookPlaceWriting:"Коринф",
bookChapters:"5",
bookVerses:"89",
bookAllWords:"1424",
bookCovenant:"НЗ",
bookGanre:"Эпистолярный"}
{bookName:"2-е Фессалоникийцам",
bookKeyVerse:"2;1-2",
bookSubject:"День  Господень",
bookKeyWord:"наступление",
bookMainTheme:"Отношение Церкви  к Дню Господнему",
BookDateWriting:" c. ad 50-ad 54  ",
bookAuthor:"Павел",
bookRecipient:"Христианам Фессалоники",
bookPlaceWriting:"Коринф",
bookChapters:"3",
bookVerses:"47",
bookAllWords:"768",
bookCovenant:"НЗ",
bookGanre:"Эпистолярный"}
{bookName:"1-е Тимофею",
bookKeyVerse:"3,15",
bookSubject:"Дом Божий",
bookKeyWord:"служение",
bookMainTheme:"Служение в Доме Божьем",
BookDateWriting:" c. ad 64  ",
bookAuthor:"Павел",
bookRecipient:"Тимофею",
bookPlaceWriting:"Рим",
bookChapters:"6",
bookVerses:"113",
bookAllWords:"1645",
bookCovenant:"НЗ",
bookGanre:"Эпистолярный"}
{bookName:"2-е Тимофею",
bookKeyVerse:"3,17",
bookSubject:"Человек Божий ",
bookKeyWord:"Совершен",
bookMainTheme:"Зрелость Божьего человека",
BookDateWriting:" c. ad 65-ad 67  ",
bookAuthor:"Павел",
bookRecipient:"Тимофею",
bookPlaceWriting:"В заключении в Риме",
bookChapters:"4",
bookVerses:"83",
bookAllWords:"1175",
bookCovenant:"НЗ",
bookGanre:"Эпистолярный"}
{bookName:"Титу",
bookKeyVerse:"2,7-8",
bookSubject:"Образец",
bookKeyWord:"во всем",
bookMainTheme:"Личный образец во всем",
BookDateWriting:" c. ad 64  ",
bookAuthor:"Павел",
bookRecipient:"Титу",
bookPlaceWriting:"Рим",
bookChapters:"3",
bookVerses:"46",
bookAllWords:"667",
bookCovenant:"НЗ",
bookGanre:"Эпистолярный"}
{bookName:"Филимону",
bookKeyVerse:"16",
bookSubject:"Принятие",
bookKeyWord:"как брата",
bookMainTheme:"Принятие как брата",
BookDateWriting:" c. ad 60  ",
bookAuthor:"Павел",
bookRecipient:"Филимону",
bookPlaceWriting:"В заключении в Риме",
bookChapters:"1",
bookVerses:"25",
bookAllWords:"337",
bookCovenant:"НЗ",
bookGanre:"Эпистолярный"}
{bookName:"Евреям",
bookKeyVerse:"8,6",
bookSubject:"Завет",
bookKeyWord:"лучший",
bookMainTheme:"Лучший завет",
BookDateWriting:"c. ad 60-ad 69",
bookAuthor:"Неизвестен",
bookRecipient:"Евреям-христианам в Риме и Иерусалиме",
bookPlaceWriting:"Неизвестно",
bookChapters:"13",
bookVerses:"303",
bookAllWords:"4810",
bookCovenant:"НЗ",
bookGanre:"Эпистолярный"}
{bookName:"Послание Иакова",
bookKeyVerse:"2,17",
bookSubject:"Вера",
bookKeyWord:"в делах",
bookMainTheme:"Вера проявленная в делах",
BookDateWriting:" c. ad 48  ",
bookAuthor:"Иаков",
bookRecipient:"Евреям-христианам в рассеянии",
bookPlaceWriting:"Иерусалим",
bookChapters:"5",
bookVerses:"108",
bookAllWords:"1674",
bookCovenant:"НЗ",
bookGanre:"Эпистолярный"}
{bookName:"1-е Петра",
bookKeyVerse:"4,13",
bookSubject:"Участие в страданиях Христовых",
bookKeyWord:"Радуйтесь",
bookMainTheme:"Радость участия в страданиях Христовых",
BookDateWriting:" c. ad 64-ad 65",
bookAuthor:"Петр",
bookRecipient:"Церквам северной малой Азии",
bookPlaceWriting:"Рим",
bookChapters:"5",
bookVerses:"105",
bookAllWords:"1691",
bookCovenant:"НЗ",
bookGanre:"Эпистолярный"}
{bookName:"2-е Петра",
bookKeyVerse:"3,17-18",
bookSubject:"Возрастание ",
bookKeyWord:"в благодати",
bookMainTheme:"Возрастание в благодати",
BookDateWriting:"c. ad 64-ad 70",
bookAuthor:"Петр",
bookRecipient:"Церквам северной малой Азии",
bookPlaceWriting:"Рим",
bookChapters:"3",
bookVerses:"61",
bookAllWords:"1076",
bookCovenant:"НЗ",
bookGanre:"Эпистолярный"}
{bookName:"1-е Иоанна",
bookKeyVerse:"2,24",
bookSubject:"Пребывание",
bookKeyWord:"в Боге",
bookMainTheme:"Пребывание в Боге",
BookDateWriting:" c. ad 85-ad 95",
bookAuthor:"Иоанн",
bookRecipient:"Христианам Ефеса",
bookPlaceWriting:"Ефес",
bookChapters:"5",
bookVerses:"105",
bookAllWords:"1965",
bookCovenant:"НЗ",
bookGanre:"Эпистолярный"}
{bookName:"2-е Иоанна",
bookKeyVerse:"6",
bookSubject:"Любовь",
bookKeyWord:"по заповедям",
bookMainTheme:"Любовь по заповедям",
BookDateWriting:" c. ad 85-ad 95",
bookAuthor:"Иоанн",
bookRecipient:"Церкви вблизи Ефеса",
bookPlaceWriting:"Ефес",
bookChapters:"1",
bookVerses:"13",
bookAllWords:"229",
bookCovenant:"НЗ",
bookGanre:"Эпистолярный"}
{bookName:"3-е Иоанна",
bookKeyVerse:"1,11",
bookSubject:"Добро",
bookKeyWord:"подражение",
bookMainTheme:"Подражание добру",
BookDateWriting:" c. ad 85-ad 95",
bookAuthor:"Иоанн",
bookRecipient:"Гаию",
bookPlaceWriting:"Ефес",
bookChapters:"1",
bookVerses:"15",
bookAllWords:"213",
bookCovenant:"НЗ",
bookGanre:"Эпистолярный"}
{bookName:"Послание Иуды",
bookKeyVerse:"3",
bookSubject:"вера",
bookKeyWord:"увещевание подвизаться",
bookMainTheme:"Увещевание подвизаться за веру",
BookDateWriting:" c. ad 60-ad 95",
bookAuthor:"Иуд",
bookRecipient:"Христианам мира",
bookPlaceWriting:"Неизвестно",
bookChapters:"1",
bookVerses:"25",
bookAllWords:"436",
bookCovenant:"НЗ",
bookGanre:"Эпистолярный"}
{bookName:"Откровение",
bookKeyVerse:"1,1",
bookSubject:"Откровение",
bookKeyWord:"Иисуса Христа",
bookMainTheme:"Откровение Иисуса Христа",
BookDateWriting:" c. ad 96 or c. ad 69",
bookAuthor:"Иоанн",
bookRecipient:"Пасторам 7 церквей",
bookPlaceWriting:"Остров Патмос",
bookChapters:"22",
bookVerses:"404",
bookAllWords:"8616",
bookCovenant:"НЗ",
bookGanre:"Апокалитические"}
